(nautobot-docker-compose-py3.10) nautobot-docker-compose$ invoke build --no-cache
Building Nautobot 2.3.6 with Python 3.12...
Running docker compose command "build --no-cache"
#0 building with "desktop-linux" instance using docker driver

#1 [nautobot internal] load build definition from Dockerfile
#1 transferring dockerfile: 2.32kB done
#1 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 3)
#1 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 14)
#1 WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 54)
#1 WARN: InvalidDefaultArgInFrom: Default value for ARG ghcr.io/nautobot/nautobot:${NAUTOBOT_VERSION}-py${PYTHON_VER} results in empty or invalid base image name (line 3)
#1 WARN: InvalidDefaultArgInFrom: Default value for ARG ghcr.io/nautobot/nautobot-dev:${NAUTOBOT_VERSION}-py${PYTHON_VER} results in empty or invalid base image name (line 14)
#1 DONE 0.0s

#2 [nautobot internal] load metadata for ghcr.io/nautobot/nautobot:2.3.6-py3.12
#2 DONE 1.0s

#3 [nautobot internal] load metadata for ghcr.io/nautobot/nautobot-dev:2.3.6-py3.12
#3 DONE 1.0s

#4 [nautobot internal] load .dockerignore
#4 transferring context: 326B done
#4 DONE 0.0s

#5 [nautobot nautobot-base 1/2] FROM ghcr.io/nautobot/nautobot:2.3.6-py3.12@sha256:f6b0ee939035529c1b53cd473a3f7069586e5e0abf4f318dbf3aa6a77b243f8e
#5 CACHED

#6 [nautobot builder 1/8] FROM ghcr.io/nautobot/nautobot-dev:2.3.6-py3.12@sha256:96544766033cfc039a22cba41c2ab386c593be3afe46ac172b7b702dc940ffcc
#6 CACHED

#7 [nautobot internal] load build context
#7 transferring context: 2.50kB done
#7 DONE 0.0s

#8 [nautobot nautobot-base 2/2] RUN apt-get update &&     apt-get upgrade -y &&     apt-get autoremove -y &&     apt-get clean all &&     rm -rf /var/lib/apt/lists/* &&     pip --no-cache-dir install --upgrade pip wheel
#8 0.628 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#8 0.737 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
#8 0.781 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#8 0.824 Get:4 http://deb.debian.org/debian bookworm/main arm64 Packages [8688 kB]
#8 1.155 Get:5 http://deb.debian.org/debian bookworm-updates/main arm64 Packages [2468 B]
#8 1.156 Get:6 http://deb.debian.org/debian-security bookworm-security/main arm64 Packages [203 kB]
#8 1.966 Fetched 9147 kB in 2s (5196 kB/s)
#8 1.966 Reading package lists...
#8 2.429 Reading package lists...
#8 2.858 Building dependency tree...
#8 2.977 Reading state information...
#8 3.010 Calculating upgrade...
#8 3.444 The following packages will be upgraded:
#8 3.444   base-files bsdutils curl libblkid1 libc-bin libc-dev-bin libc6 libc6-dev
#8 3.444   libcurl3-gnutls libcurl4 libmount1 libnghttp2-14 libnss3 libnss3-dev
#8 3.444   libsmartcols1 libsqlite3-0 libssl-dev libssl3 libsystemd0 libudev1 libuuid1
#8 3.445   linux-libc-dev mount openssl util-linux util-linux-extra
#8 3.556 26 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
#8 3.556 Need to get 17.6 MB of archives.
#8 3.556 After this operation, 52.2 kB of additional disk space will be used.
#8 3.556 Get:1 http://deb.debian.org/debian bookworm/main arm64 base-files arm64 12.4+deb12u8 [70.9 kB]
#8 3.654 Get:2 http://deb.debian.org/debian bookworm/main arm64 bsdutils arm64 1:2.38.1-5+deb12u2 [94.4 kB]
#8 3.670 Get:3 http://deb.debian.org/debian bookworm/main arm64 libc6-dev arm64 2.36-9+deb12u9 [1431 kB]
#8 3.837 Get:4 http://deb.debian.org/debian bookworm/main arm64 libc-dev-bin arm64 2.36-9+deb12u9 [45.9 kB]
#8 3.838 Get:5 http://deb.debian.org/debian-security bookworm-security/main arm64 linux-libc-dev arm64 6.1.119-1 [2050 kB]
#8 3.915 Get:6 http://deb.debian.org/debian bookworm/main arm64 libc6 arm64 2.36-9+deb12u9 [2325 kB]
#8 3.955 Get:7 http://deb.debian.org/debian bookworm/main arm64 libsmartcols1 arm64 2.38.1-5+deb12u2 [104 kB]
#8 3.960 Get:8 http://deb.debian.org/debian bookworm/main arm64 util-linux-extra arm64 2.38.1-5+deb12u2 [112 kB]
#8 3.964 Get:9 http://deb.debian.org/debian bookworm/main arm64 util-linux arm64 2.38.1-5+deb12u2 [1145 kB]
#8 3.980 Get:10 http://deb.debian.org/debian bookworm/main arm64 libc-bin arm64 2.36-9+deb12u9 [532 kB]
#8 3.987 Get:11 http://deb.debian.org/debian bookworm/main arm64 mount arm64 2.38.1-5+deb12u2 [134 kB]
#8 3.988 Get:12 http://deb.debian.org/debian bookworm/main arm64 libblkid1 arm64 2.38.1-5+deb12u2 [143 kB]
#8 3.991 Get:13 http://deb.debian.org/debian bookworm/main arm64 libmount1 arm64 2.38.1-5+deb12u2 [159 kB]
#8 3.992 Get:14 http://deb.debian.org/debian bookworm/main arm64 libsystemd0 arm64 252.31-1~deb12u1 [308 kB]
#8 3.999 Get:15 http://deb.debian.org/debian bookworm/main arm64 libudev1 arm64 252.31-1~deb12u1 [103 kB]
#8 4.010 Get:16 http://deb.debian.org/debian bookworm/main arm64 libuuid1 arm64 2.38.1-5+deb12u2 [28.4 kB]
#8 4.015 Get:17 http://deb.debian.org/debian bookworm/main arm64 libnghttp2-14 arm64 1.52.0-1+deb12u2 [68.6 kB]
#8 4.017 Get:18 http://deb.debian.org/debian bookworm/main arm64 libssl-dev arm64 3.0.15-1~deb12u1 [2308 kB]
#8 4.054 Get:19 http://deb.debian.org/debian bookworm/main arm64 libssl3 arm64 3.0.15-1~deb12u1 [1811 kB]
#8 4.089 Get:20 http://deb.debian.org/debian bookworm/main arm64 curl arm64 7.88.1-10+deb12u8 [309 kB]
#8 4.100 Get:21 http://deb.debian.org/debian bookworm/main arm64 libcurl4 arm64 7.88.1-10+deb12u8 [365 kB]
#8 4.114 Get:22 http://deb.debian.org/debian bookworm/main arm64 libcurl3-gnutls arm64 7.88.1-10+deb12u8 [360 kB]
#8 4.127 Get:23 http://deb.debian.org/debian-security bookworm-security/main arm64 libnss3-dev arm64 2:3.87.1-1+deb12u1 [245 kB]
#8 4.131 Get:24 http://deb.debian.org/debian bookworm/main arm64 libsqlite3-0 arm64 3.40.1-2+deb12u1 [785 kB]
#8 4.148 Get:25 http://deb.debian.org/debian-security bookworm-security/main arm64 libnss3 arm64 2:3.87.1-1+deb12u1 [1218 kB]
#8 4.178 Get:26 http://deb.debian.org/debian bookworm/main arm64 openssl arm64 3.0.15-1~deb12u1 [1392 kB]
#8 4.408 debconf: delaying package configuration, since apt-utils is not installed
#8 4.433 Fetched 17.6 MB in 1s (23.0 MB/s)
(Reading database ... 13008 files and directories currently installed.)
#8 4.464 Preparing to unpack .../base-files_12.4+deb12u8_arm64.deb ...
#8 4.470 Unpacking base-files (12.4+deb12u8) over (12.4+deb12u7) ...
#8 4.543 Setting up base-files (12.4+deb12u8) ...
#8 4.544 Installing new version of config file /etc/debian_version ...
(Reading database ... 13008 files and directories currently installed.)
#8 4.587 Preparing to unpack .../bsdutils_1%3a2.38.1-5+deb12u2_arm64.deb ...
#8 4.595 Unpacking bsdutils (1:2.38.1-5+deb12u2) over (1:2.38.1-5+deb12u1) ...
#8 4.636 Setting up bsdutils (1:2.38.1-5+deb12u2) ...
(Reading database ... 13008 files and directories currently installed.)
#8 4.663 Preparing to unpack .../libc6-dev_2.36-9+deb12u9_arm64.deb ...
#8 4.669 Unpacking libc6-dev:arm64 (2.36-9+deb12u9) over (2.36-9+deb12u8) ...
#8 5.426 Preparing to unpack .../libc-dev-bin_2.36-9+deb12u9_arm64.deb ...
#8 5.433 Unpacking libc-dev-bin (2.36-9+deb12u9) over (2.36-9+deb12u8) ...
#8 5.461 Preparing to unpack .../linux-libc-dev_6.1.119-1_arm64.deb ...
#8 5.468 Unpacking linux-libc-dev:arm64 (6.1.119-1) over (6.1.106-3) ...
#8 6.922 Preparing to unpack .../libc6_2.36-9+deb12u9_arm64.deb ...
#8 6.973 debconf: unable to initialize frontend: Dialog
#8 6.973 debconf: (TERM is not set, so the dialog frontend is not usable.)
#8 6.973 debconf: falling back to frontend: Readline
#8 6.977 debconf: unable to initialize frontend: Readline
#8 6.977 debconf: (This frontend requires a controlling tty.)
#8 6.977 debconf: falling back to frontend: Teletype
#8 7.002 Unpacking libc6:arm64 (2.36-9+deb12u9) over (2.36-9+deb12u8) ...
#8 7.693 Setting up libc6:arm64 (2.36-9+deb12u9) ...
#8 7.761 debconf: unable to initialize frontend: Dialog
#8 7.761 debconf: (TERM is not set, so the dialog frontend is not usable.)
#8 7.761 debconf: falling back to frontend: Readline
#8 7.766 debconf: unable to initialize frontend: Readline
#8 7.766 debconf: (This frontend requires a controlling tty.)
#8 7.766 debconf: falling back to frontend: Teletype
(Reading database ... 13008 files and directories currently installed.)
#8 8.826 Preparing to unpack .../libsmartcols1_2.38.1-5+deb12u2_arm64.deb ...
#8 8.831 Unpacking libsmartcols1:arm64 (2.38.1-5+deb12u2) over (2.38.1-5+deb12u1) ...
#8 8.858 Setting up libsmartcols1:arm64 (2.38.1-5+deb12u2) ...
(Reading database ... 13008 files and directories currently installed.)
#8 8.877 Preparing to unpack .../util-linux-extra_2.38.1-5+deb12u2_arm64.deb ...
#8 8.883 Unpacking util-linux-extra (2.38.1-5+deb12u2) over (2.38.1-5+deb12u1) ...
#8 8.919 Setting up util-linux-extra (2.38.1-5+deb12u2) ...
(Reading database ... 13008 files and directories currently installed.)
#8 8.948 Preparing to unpack .../util-linux_2.38.1-5+deb12u2_arm64.deb ...
#8 8.952 Unpacking util-linux (2.38.1-5+deb12u2) over (2.38.1-5+deb12u1) ...
#8 9.181 Setting up util-linux (2.38.1-5+deb12u2) ...
#8 9.193 update-alternatives: warning: forcing reinstallation of alternative /bin/more because link group pager is broken
#8 9.194 update-alternatives: warning: skip creation of /usr/share/man/man1/pager.1.gz because associated file /usr/share/man/man1/more.1.gz (of link group pager) doesn't exist
(Reading database ... 13008 files and directories currently installed.)
#8 9.280 Preparing to unpack .../libc-bin_2.36-9+deb12u9_arm64.deb ...
#8 9.287 Unpacking libc-bin (2.36-9+deb12u9) over (2.36-9+deb12u8) ...
#8 9.381 Setting up libc-bin (2.36-9+deb12u9) ...
(Reading database ... 13008 files and directories currently installed.)
#8 9.438 Preparing to unpack .../mount_2.38.1-5+deb12u2_arm64.deb ...
#8 9.443 Unpacking mount (2.38.1-5+deb12u2) over (2.38.1-5+deb12u1) ...
#8 9.479 Preparing to unpack .../libblkid1_2.38.1-5+deb12u2_arm64.deb ...
#8 9.485 Unpacking libblkid1:arm64 (2.38.1-5+deb12u2) over (2.38.1-5+deb12u1) ...
#8 9.519 Setting up libblkid1:arm64 (2.38.1-5+deb12u2) ...
(Reading database ... 13008 files and directories currently installed.)
#8 9.544 Preparing to unpack .../libmount1_2.38.1-5+deb12u2_arm64.deb ...
#8 9.552 Unpacking libmount1:arm64 (2.38.1-5+deb12u2) over (2.38.1-5+deb12u1) ...
#8 9.587 Setting up libmount1:arm64 (2.38.1-5+deb12u2) ...
(Reading database ... 13008 files and directories currently installed.)
#8 9.622 Preparing to unpack .../libsystemd0_252.31-1~deb12u1_arm64.deb ...
#8 9.629 Unpacking libsystemd0:arm64 (252.31-1~deb12u1) over (252.30-1~deb12u2) ...
#8 9.676 Setting up libsystemd0:arm64 (252.31-1~deb12u1) ...
(Reading database ... 13008 files and directories currently installed.)
#8 9.705 Preparing to unpack .../libudev1_252.31-1~deb12u1_arm64.deb ...
#8 9.717 Unpacking libudev1:arm64 (252.31-1~deb12u1) over (252.30-1~deb12u2) ...
#8 9.762 Setting up libudev1:arm64 (252.31-1~deb12u1) ...
(Reading database ... 13008 files and directories currently installed.)
#8 9.790 Preparing to unpack .../libuuid1_2.38.1-5+deb12u2_arm64.deb ...
#8 9.795 Unpacking libuuid1:arm64 (2.38.1-5+deb12u2) over (2.38.1-5+deb12u1) ...
#8 9.817 Setting up libuuid1:arm64 (2.38.1-5+deb12u2) ...
(Reading database ... 13008 files and directories currently installed.)
#8 9.840 Preparing to unpack .../0-libnghttp2-14_1.52.0-1+deb12u2_arm64.deb ...
#8 9.845 Unpacking libnghttp2-14:arm64 (1.52.0-1+deb12u2) over (1.52.0-1+deb12u1) ...
#8 9.870 Preparing to unpack .../1-libssl-dev_3.0.15-1~deb12u1_arm64.deb ...
#8 9.876 Unpacking libssl-dev:arm64 (3.0.15-1~deb12u1) over (3.0.14-1~deb12u2) ...
#8 ...

#9 [nautobot builder 2/8] RUN apt-get update &&     apt-get upgrade -y &&     apt-get autoremove -y &&     apt-get clean all &&     rm -rf /var/lib/apt/lists/*
#9 0.638 Get:1 http://deb.debian.org/debian bookworm InRelease [151 kB]
#9 0.780 Get:2 http://deb.debian.org/debian bookworm-updates InRelease [55.4 kB]
#9 0.829 Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
#9 0.881 Get:4 http://deb.debian.org/debian bookworm/main arm64 Packages [8688 kB]
#9 1.190 Get:5 http://deb.debian.org/debian bookworm-updates/main arm64 Packages [2468 B]
#9 1.235 Get:6 http://deb.debian.org/debian-security bookworm-security/main arm64 Packages [203 kB]
#9 2.041 Fetched 9147 kB in 2s (4984 kB/s)
#9 2.041 Reading package lists...
#9 2.509 Reading package lists...
#9 2.990 Building dependency tree...
#9 3.098 Reading state information...
#9 3.118 Calculating upgrade...
#9 3.606 The following packages will be upgraded:
#9 3.606   base-files bsdutils curl libblkid1 libc-bin libc-dev-bin libc6 libc6-dev
#9 3.606   libcurl3-gnutls libcurl4 libmount1 libnghttp2-14 libnss3 libnss3-dev
#9 3.606   libpython3.11-minimal libpython3.11-stdlib libsmartcols1 libsqlite3-0
#9 3.606   libssl-dev libssl3 libsystemd0 libudev1 libuuid1 linux-libc-dev mount
#9 3.607   node-es-module-lexer node-globby openssl python3.11 python3.11-minimal
#9 3.607   util-linux util-linux-extra
#9 3.717 32 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
#9 3.717 Need to get 22.7 MB of archives.
#9 3.717 After this operation, 52.2 kB of additional disk space will be used.
#9 3.717 Get:1 http://deb.debian.org/debian bookworm/main arm64 base-files arm64 12.4+deb12u8 [70.9 kB]
#9 3.821 Get:2 http://deb.debian.org/debian bookworm/main arm64 bsdutils arm64 1:2.38.1-5+deb12u2 [94.4 kB]
#9 3.849 Get:3 http://deb.debian.org/debian bookworm/main arm64 libc6-dev arm64 2.36-9+deb12u9 [1431 kB]
#9 4.050 Get:4 http://deb.debian.org/debian bookworm/main arm64 libc-dev-bin arm64 2.36-9+deb12u9 [45.9 kB]
#9 4.050 Get:5 http://deb.debian.org/debian-security bookworm-security/main arm64 linux-libc-dev arm64 6.1.119-1 [2050 kB]
#9 4.191 Get:6 http://deb.debian.org/debian bookworm/main arm64 libc6 arm64 2.36-9+deb12u9 [2325 kB]
#9 4.276 Get:7 http://deb.debian.org/debian bookworm/main arm64 libsmartcols1 arm64 2.38.1-5+deb12u2 [104 kB]
#9 4.280 Get:8 http://deb.debian.org/debian bookworm/main arm64 util-linux-extra arm64 2.38.1-5+deb12u2 [112 kB]
#9 4.281 Get:9 http://deb.debian.org/debian bookworm/main arm64 util-linux arm64 2.38.1-5+deb12u2 [1145 kB]
#9 4.299 Get:10 http://deb.debian.org/debian bookworm/main arm64 libc-bin arm64 2.36-9+deb12u9 [532 kB]
#9 4.311 Get:11 http://deb.debian.org/debian bookworm/main arm64 mount arm64 2.38.1-5+deb12u2 [134 kB]
#9 4.313 Get:12 http://deb.debian.org/debian bookworm/main arm64 libssl-dev arm64 3.0.15-1~deb12u1 [2308 kB]
#9 4.377 Get:13 http://deb.debian.org/debian bookworm/main arm64 libssl3 arm64 3.0.15-1~deb12u1 [1811 kB]
#9 4.417 Get:14 http://deb.debian.org/debian bookworm/main arm64 python3.11 arm64 3.11.2-6+deb12u4 [573 kB]
#9 4.426 Get:15 http://deb.debian.org/debian bookworm/main arm64 libpython3.11-stdlib arm64 3.11.2-6+deb12u4 [1746 kB]
#9 4.463 Get:16 http://deb.debian.org/debian bookworm/main arm64 python3.11-minimal arm64 3.11.2-6+deb12u4 [1860 kB]
#9 4.496 Get:17 http://deb.debian.org/debian bookworm/main arm64 libpython3.11-minimal arm64 3.11.2-6+deb12u4 [808 kB]
#9 4.509 Get:18 http://deb.debian.org/debian bookworm/main arm64 libsqlite3-0 arm64 3.40.1-2+deb12u1 [785 kB]
#9 4.522 Get:19 http://deb.debian.org/debian bookworm/main arm64 libuuid1 arm64 2.38.1-5+deb12u2 [28.4 kB]
#9 4.522 Get:20 http://deb.debian.org/debian bookworm/main arm64 libblkid1 arm64 2.38.1-5+deb12u2 [143 kB]
#9 4.523 Get:21 http://deb.debian.org/debian bookworm/main arm64 libmount1 arm64 2.38.1-5+deb12u2 [159 kB]
#9 4.525 Get:22 http://deb.debian.org/debian bookworm/main arm64 libsystemd0 arm64 252.31-1~deb12u1 [308 kB]
#9 4.528 Get:23 http://deb.debian.org/debian bookworm/main arm64 libudev1 arm64 252.31-1~deb12u1 [103 kB]
#9 4.529 Get:24 http://deb.debian.org/debian bookworm/main arm64 libnghttp2-14 arm64 1.52.0-1+deb12u2 [68.6 kB]
#9 4.531 Get:25 http://deb.debian.org/debian bookworm/main arm64 curl arm64 7.88.1-10+deb12u8 [309 kB]
#9 4.563 Get:26 http://deb.debian.org/debian bookworm/main arm64 libcurl4 arm64 7.88.1-10+deb12u8 [365 kB]
#9 4.575 Get:27 http://deb.debian.org/debian bookworm/main arm64 libcurl3-gnutls arm64 7.88.1-10+deb12u8 [360 kB]
#9 4.590 Get:28 http://deb.debian.org/debian-security bookworm-security/main arm64 libnss3-dev arm64 2:3.87.1-1+deb12u1 [245 kB]
#9 4.591 Get:29 http://deb.debian.org/debian-security bookworm-security/main arm64 libnss3 arm64 2:3.87.1-1+deb12u1 [1218 kB]
#9 4.618 Get:30 http://deb.debian.org/debian bookworm/main arm64 node-es-module-lexer all 1.1.0+dfsg-2+deb12u1 [19.7 kB]
#9 4.724 Get:31 http://deb.debian.org/debian bookworm/main arm64 node-globby all 13.1.3+~cs16.25.40-1+deb12u1 [40.5 kB]
#9 4.725 Get:32 http://deb.debian.org/debian bookworm/main arm64 openssl arm64 3.0.15-1~deb12u1 [1392 kB]
#9 4.922 debconf: delaying package configuration, since apt-utils is not installed
#9 4.944 Fetched 22.7 MB in 1s (20.0 MB/s)
(Reading database ... 44936 files and directories currently installed.)
#9 5.016 Preparing to unpack .../base-files_12.4+deb12u8_arm64.deb ...
#9 5.022 Unpacking base-files (12.4+deb12u8) over (12.4+deb12u7) ...
#9 5.104 Setting up base-files (12.4+deb12u8) ...
#9 5.108 Installing new version of config file /etc/debian_version ...
(Reading database ... 44936 files and directories currently installed.)
#9 5.158 Preparing to unpack .../bsdutils_1%3a2.38.1-5+deb12u2_arm64.deb ...
#9 5.164 Unpacking bsdutils (1:2.38.1-5+deb12u2) over (1:2.38.1-5+deb12u1) ...
#9 5.222 Setting up bsdutils (1:2.38.1-5+deb12u2) ...
(Reading database ... 44936 files and directories currently installed.)
#9 5.269 Preparing to unpack .../libc6-dev_2.36-9+deb12u9_arm64.deb ...
#9 5.275 Unpacking libc6-dev:arm64 (2.36-9+deb12u9) over (2.36-9+deb12u8) ...
#9 6.175 Preparing to unpack .../libc-dev-bin_2.36-9+deb12u9_arm64.deb ...
#9 6.182 Unpacking libc-dev-bin (2.36-9+deb12u9) over (2.36-9+deb12u8) ...
#9 6.210 Preparing to unpack .../linux-libc-dev_6.1.119-1_arm64.deb ...
#9 6.217 Unpacking linux-libc-dev:arm64 (6.1.119-1) over (6.1.106-3) ...
#9 7.476 Preparing to unpack .../libc6_2.36-9+deb12u9_arm64.deb ...
#9 7.531 debconf: unable to initialize frontend: Dialog
#9 7.531 debconf: (TERM is not set, so the dialog frontend is not usable.)
#9 7.531 debconf: falling back to frontend: Readline
#9 7.536 debconf: unable to initialize frontend: Readline
#9 7.536 debconf: (This frontend requires a controlling tty.)
#9 7.536 debconf: falling back to frontend: Teletype
#9 7.649 Unpacking libc6:arm64 (2.36-9+deb12u9) over (2.36-9+deb12u8) ...
#9 8.153 Setting up libc6:arm64 (2.36-9+deb12u9) ...
#9 8.203 debconf: unable to initialize frontend: Dialog
#9 8.203 debconf: (TERM is not set, so the dialog frontend is not usable.)
#9 8.203 debconf: falling back to frontend: Readline
#9 8.207 debconf: unable to initialize frontend: Readline
#9 8.207 debconf: (This frontend requires a controlling tty.)
#9 8.207 debconf: falling back to frontend: Teletype
(Reading database ... 44936 files and directories currently installed.)
#9 9.261 Preparing to unpack .../libsmartcols1_2.38.1-5+deb12u2_arm64.deb ...
#9 9.266 Unpacking libsmartcols1:arm64 (2.38.1-5+deb12u2) over (2.38.1-5+deb12u1) ...
#9 9.301 Setting up libsmartcols1:arm64 (2.38.1-5+deb12u2) ...
(Reading database ... 44936 files and directories currently installed.)
#9 9.352 Preparing to unpack .../util-linux-extra_2.38.1-5+deb12u2_arm64.deb ...
#9 9.361 Unpacking util-linux-extra (2.38.1-5+deb12u2) over (2.38.1-5+deb12u1) ...
#9 9.417 Setting up util-linux-extra (2.38.1-5+deb12u2) ...
(Reading database ... 44936 files and directories currently installed.)
#9 9.474 Preparing to unpack .../util-linux_2.38.1-5+deb12u2_arm64.deb ...
#9 9.480 Unpacking util-linux (2.38.1-5+deb12u2) over (2.38.1-5+deb12u1) ...
#9 9.755 Setting up util-linux (2.38.1-5+deb12u2) ...
#9 9.773 update-alternatives: warning: forcing reinstallation of alternative /bin/more because link group pager is broken
#9 9.774 update-alternatives: warning: skip creation of /usr/share/man/man1/pager.1.gz because associated file /usr/share/man/man1/more.1.gz (of link group pager) doesn't exist
(Reading database ... 44936 files and directories currently installed.)
#9 9.892 Preparing to unpack .../libc-bin_2.36-9+deb12u9_arm64.deb ...
#9 9.897 Unpacking libc-bin (2.36-9+deb12u9) over (2.36-9+deb12u8) ...
#9 9.986 Setting up libc-bin (2.36-9+deb12u9) ...
(Reading database ... 44936 files and directories currently installed.)
#9 10.06 Preparing to unpack .../0-mount_2.38.1-5+deb12u2_arm64.deb ...
#9 10.07 Unpacking mount (2.38.1-5+deb12u2) over (2.38.1-5+deb12u1) ...
#9 10.12 Preparing to unpack .../1-libssl-dev_3.0.15-1~deb12u1_arm64.deb ...
#9 10.13 Unpacking libssl-dev:arm64 (3.0.15-1~deb12u1) over (3.0.14-1~deb12u2) ...
#9 ...

#8 [nautobot nautobot-base 2/2] RUN apt-get update &&     apt-get upgrade -y &&     apt-get autoremove -y &&     apt-get clean all &&     rm -rf /var/lib/apt/lists/* &&     pip --no-cache-dir install --upgrade pip wheel
#8 10.16 Preparing to unpack .../2-libssl3_3.0.15-1~deb12u1_arm64.deb ...
#8 10.16 Unpacking libssl3:arm64 (3.0.15-1~deb12u1) over (3.0.14-1~deb12u2) ...
#8 10.29 Preparing to unpack .../3-curl_7.88.1-10+deb12u8_arm64.deb ...
#8 10.29 Unpacking curl (7.88.1-10+deb12u8) over (7.88.1-10+deb12u7) ...
#8 10.35 Preparing to unpack .../4-libcurl4_7.88.1-10+deb12u8_arm64.deb ...
#8 10.36 Unpacking libcurl4:arm64 (7.88.1-10+deb12u8) over (7.88.1-10+deb12u7) ...
#8 10.40 Preparing to unpack .../5-libcurl3-gnutls_7.88.1-10+deb12u8_arm64.deb ...
#8 10.40 Unpacking libcurl3-gnutls:arm64 (7.88.1-10+deb12u8) over (7.88.1-10+deb12u7) ...
#8 10.44 Preparing to unpack .../6-libnss3-dev_2%3a3.87.1-1+deb12u1_arm64.deb ...
#8 10.44 Unpacking libnss3-dev:arm64 (2:3.87.1-1+deb12u1) over (2:3.87.1-1) ...
#8 10.60 Preparing to unpack .../7-libsqlite3-0_3.40.1-2+deb12u1_arm64.deb ...
#8 10.60 Unpacking libsqlite3-0:arm64 (3.40.1-2+deb12u1) over (3.40.1-2) ...
#8 10.68 Preparing to unpack .../8-libnss3_2%3a3.87.1-1+deb12u1_arm64.deb ...
#8 10.69 Unpacking libnss3:arm64 (2:3.87.1-1+deb12u1) over (2:3.87.1-1) ...
#8 10.80 Preparing to unpack .../9-openssl_3.0.15-1~deb12u1_arm64.deb ...
#8 10.81 Unpacking openssl (3.0.15-1~deb12u1) over (3.0.14-1~deb12u2) ...
#8 10.90 Setting up libsqlite3-0:arm64 (3.40.1-2+deb12u1) ...
#8 10.90 Setting up libssl3:arm64 (3.0.15-1~deb12u1) ...
#8 10.91 Setting up libnghttp2-14:arm64 (1.52.0-1+deb12u2) ...
#8 10.91 Setting up linux-libc-dev:arm64 (6.1.119-1) ...
#8 10.92 Setting up libcurl3-gnutls:arm64 (7.88.1-10+deb12u8) ...
#8 10.93 Setting up libnss3:arm64 (2:3.87.1-1+deb12u1) ...
#8 10.93 Setting up libssl-dev:arm64 (3.0.15-1~deb12u1) ...
#8 10.94 Setting up mount (2.38.1-5+deb12u2) ...
#8 10.95 Setting up libnss3-dev:arm64 (2:3.87.1-1+deb12u1) ...
#8 10.95 Setting up libcurl4:arm64 (7.88.1-10+deb12u8) ...
#8 10.96 Setting up curl (7.88.1-10+deb12u8) ...
#8 10.96 Setting up libc-dev-bin (2.36-9+deb12u9) ...
#8 10.97 Setting up openssl (3.0.15-1~deb12u1) ...
#8 10.98 Setting up libc6-dev:arm64 (2.36-9+deb12u9) ...
#8 10.98 Processing triggers for libc-bin (2.36-9+deb12u9) ...
#8 10.99 Processing triggers for mailcap (3.70+nmu1) ...
#8 11.02 Reading package lists...
#8 11.49 Building dependency tree...
#8 11.59 Reading state information...
#8 11.75 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
#8 12.11 Requirement already satisfied: pip in /usr/local/lib/python3.12/site-packages (24.2)
#8 12.34 Collecting pip
#8 12.82   Downloading pip-24.3.1-py3-none-any.whl.metadata (3.7 kB)
#8 12.82 Requirement already satisfied: wheel in /usr/local/lib/python3.12/site-packages (0.44.0)
#8 12.90 Collecting wheel
#8 12.94   Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
#8 12.99 Downloading pip-24.3.1-py3-none-any.whl (1.8 MB)
#8 13.21    ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.8/1.8 MB 13.7 MB/s eta 0:00:00
#8 13.27 Downloading wheel-0.45.1-py3-none-any.whl (72 kB)
#8 13.38 Installing collected packages: wheel, pip
#8 13.38   Attempting uninstall: wheel
#8 13.39     Found existing installation: wheel 0.44.0
#8 13.39     Uninstalling wheel-0.44.0:
#8 13.42       Successfully uninstalled wheel-0.44.0
#8 13.46   Attempting uninstall: pip
#8 13.46     Found existing installation: pip 24.2
#8 13.48     Uninstalling pip-24.2:
#8 13.68       Successfully uninstalled pip-24.2
#8 14.44 Successfully installed pip-24.3.1 wheel-0.45.1
#8 14.44 WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
#8 DONE 14.8s

#9 [nautobot builder 2/8] RUN apt-get update &&     apt-get upgrade -y &&     apt-get autoremove -y &&     apt-get clean all &&     rm -rf /var/lib/apt/lists/*
#9 10.37 Preparing to unpack .../2-libssl3_3.0.15-1~deb12u1_arm64.deb ...
#9 10.37 Unpacking libssl3:arm64 (3.0.15-1~deb12u1) over (3.0.14-1~deb12u2) ...
#9 10.49 Preparing to unpack .../3-python3.11_3.11.2-6+deb12u4_arm64.deb ...
#9 10.59 Unpacking python3.11 (3.11.2-6+deb12u4) over (3.11.2-6+deb12u3) ...
#9 10.62 Preparing to unpack .../4-libpython3.11-stdlib_3.11.2-6+deb12u4_arm64.deb ...
#9 10.65 Unpacking libpython3.11-stdlib:arm64 (3.11.2-6+deb12u4) over (3.11.2-6+deb12u3) ...
#9 11.12 Preparing to unpack .../5-python3.11-minimal_3.11.2-6+deb12u4_arm64.deb ...
#9 11.14 Unpacking python3.11-minimal (3.11.2-6+deb12u4) over (3.11.2-6+deb12u3) ...
#9 11.30 Preparing to unpack .../6-libpython3.11-minimal_3.11.2-6+deb12u4_arm64.deb ...
#9 11.35 Unpacking libpython3.11-minimal:arm64 (3.11.2-6+deb12u4) over (3.11.2-6+deb12u3) ...
#9 11.63 Preparing to unpack .../7-libsqlite3-0_3.40.1-2+deb12u1_arm64.deb ...
#9 11.64 Unpacking libsqlite3-0:arm64 (3.40.1-2+deb12u1) over (3.40.1-2) ...
#9 11.70 Preparing to unpack .../8-libuuid1_2.38.1-5+deb12u2_arm64.deb ...
#9 11.70 Unpacking libuuid1:arm64 (2.38.1-5+deb12u2) over (2.38.1-5+deb12u1) ...
#9 11.73 Setting up libuuid1:arm64 (2.38.1-5+deb12u2) ...
(Reading database ... 44936 files and directories currently installed.)
#9 11.78 Preparing to unpack .../libblkid1_2.38.1-5+deb12u2_arm64.deb ...
#9 11.78 Unpacking libblkid1:arm64 (2.38.1-5+deb12u2) over (2.38.1-5+deb12u1) ...
#9 11.82 Setting up libblkid1:arm64 (2.38.1-5+deb12u2) ...
(Reading database ... 44936 files and directories currently installed.)
#9 11.86 Preparing to unpack .../libmount1_2.38.1-5+deb12u2_arm64.deb ...
#9 11.87 Unpacking libmount1:arm64 (2.38.1-5+deb12u2) over (2.38.1-5+deb12u1) ...
#9 11.90 Setting up libmount1:arm64 (2.38.1-5+deb12u2) ...
(Reading database ... 44936 files and directories currently installed.)
#9 11.96 Preparing to unpack .../libsystemd0_252.31-1~deb12u1_arm64.deb ...
#9 11.97 Unpacking libsystemd0:arm64 (252.31-1~deb12u1) over (252.30-1~deb12u2) ...
#9 12.02 Setting up libsystemd0:arm64 (252.31-1~deb12u1) ...
(Reading database ... 44936 files and directories currently installed.)
#9 12.07 Preparing to unpack .../libudev1_252.31-1~deb12u1_arm64.deb ...
#9 12.09 Unpacking libudev1:arm64 (252.31-1~deb12u1) over (252.30-1~deb12u2) ...
#9 12.13 Setting up libudev1:arm64 (252.31-1~deb12u1) ...
(Reading database ... 44936 files and directories currently installed.)
#9 12.19 Preparing to unpack .../0-libnghttp2-14_1.52.0-1+deb12u2_arm64.deb ...
#9 12.20 Unpacking libnghttp2-14:arm64 (1.52.0-1+deb12u2) over (1.52.0-1+deb12u1) ...
#9 12.23 Preparing to unpack .../1-curl_7.88.1-10+deb12u8_arm64.deb ...
#9 12.24 Unpacking curl (7.88.1-10+deb12u8) over (7.88.1-10+deb12u7) ...
#9 12.28 Preparing to unpack .../2-libcurl4_7.88.1-10+deb12u8_arm64.deb ...
#9 12.29 Unpacking libcurl4:arm64 (7.88.1-10+deb12u8) over (7.88.1-10+deb12u7) ...
#9 12.34 Preparing to unpack .../3-libcurl3-gnutls_7.88.1-10+deb12u8_arm64.deb ...
#9 12.34 Unpacking libcurl3-gnutls:arm64 (7.88.1-10+deb12u8) over (7.88.1-10+deb12u7) ...
#9 12.38 Preparing to unpack .../4-libnss3-dev_2%3a3.87.1-1+deb12u1_arm64.deb ...
#9 12.39 Unpacking libnss3-dev:arm64 (2:3.87.1-1+deb12u1) over (2:3.87.1-1) ...
#9 12.49 Preparing to unpack .../5-libnss3_2%3a3.87.1-1+deb12u1_arm64.deb ...
#9 12.50 Unpacking libnss3:arm64 (2:3.87.1-1+deb12u1) over (2:3.87.1-1) ...
#9 12.62 Preparing to unpack .../6-node-es-module-lexer_1.1.0+dfsg-2+deb12u1_all.deb ...
#9 12.67 Unpacking node-es-module-lexer (1.1.0+dfsg-2+deb12u1) over (1.1.0+dfsg-2) ...
#9 12.70 Preparing to unpack .../7-node-globby_13.1.3+~cs16.25.40-1+deb12u1_all.deb ...
#9 12.71 Unpacking node-globby (13.1.3+~cs16.25.40-1+deb12u1) over (13.1.3+~cs16.25.40-1) ...
#9 12.87 Preparing to unpack .../8-openssl_3.0.15-1~deb12u1_arm64.deb ...
#9 12.88 Unpacking openssl (3.0.15-1~deb12u1) over (3.0.14-1~deb12u2) ...
#9 12.98 Setting up libsqlite3-0:arm64 (3.40.1-2+deb12u1) ...
#9 12.99 Setting up node-es-module-lexer (1.1.0+dfsg-2+deb12u1) ...
#9 13.00 Setting up libssl3:arm64 (3.0.15-1~deb12u1) ...
#9 13.00 Setting up libnghttp2-14:arm64 (1.52.0-1+deb12u2) ...
#9 13.00 Setting up linux-libc-dev:arm64 (6.1.119-1) ...
#9 13.01 Setting up libcurl3-gnutls:arm64 (7.88.1-10+deb12u8) ...
#9 13.01 Setting up libnss3:arm64 (2:3.87.1-1+deb12u1) ...
#9 13.02 Setting up node-globby (13.1.3+~cs16.25.40-1+deb12u1) ...
#9 13.02 Setting up libssl-dev:arm64 (3.0.15-1~deb12u1) ...
#9 13.03 Setting up mount (2.38.1-5+deb12u2) ...
#9 13.03 Setting up libnss3-dev:arm64 (2:3.87.1-1+deb12u1) ...
#9 13.04 Setting up libcurl4:arm64 (7.88.1-10+deb12u8) ...
#9 13.04 Setting up libpython3.11-minimal:arm64 (3.11.2-6+deb12u4) ...
#9 13.05 Setting up curl (7.88.1-10+deb12u8) ...
#9 13.05 Setting up libc-dev-bin (2.36-9+deb12u9) ...
#9 13.06 Setting up openssl (3.0.15-1~deb12u1) ...
#9 13.06 Setting up python3.11-minimal (3.11.2-6+deb12u4) ...
#9 13.49 Setting up libpython3.11-stdlib:arm64 (3.11.2-6+deb12u4) ...
#9 13.50 Setting up libc6-dev:arm64 (2.36-9+deb12u9) ...
#9 13.50 Setting up python3.11 (3.11.2-6+deb12u4) ...
#9 14.00 Processing triggers for mailcap (3.70+nmu1) ...
#9 14.01 Processing triggers for libc-bin (2.36-9+deb12u9) ...
#9 14.05 Reading package lists...
#9 14.73 Building dependency tree...
#9 14.88 Reading state information...
#9 15.00 0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
#9 DONE 15.0s

#10 [nautobot builder 3/8] COPY ../pyproject.toml ../poetry.lock /source/
#10 DONE 0.0s

#11 [nautobot builder 4/8] COPY ../plugins /source/plugins
#11 DONE 0.0s

#12 [nautobot builder 5/8] RUN cd /source &&     poetry install --no-interaction --no-ansi &&     mkdir /tmp/dist &&     poetry export --without-hashes -o /tmp/dist/requirements.txt
#12 0.565 Skipping virtualenv creation, as specified in config file.
#12 0.893 Installing dependencies from lock file
#12 1.086
#12 1.086 Package operations: 29 installs, 36 updates, 0 removals
#12 1.086
#12 1.087   - Updating cffi (1.17.0rc1 -> 1.17.1)
#12 2.197   - Updating bcrypt (4.2.0 -> 4.2.1)
#12 2.198   - Updating cryptography (43.0.1 -> 43.0.3)
#12 3.003   - Updating attrs (23.2.0 -> 24.2.0)
#12 3.004   - Updating certifi (2024.7.4 -> 2024.8.30)
#12 3.005   - Updating charset-normalizer (3.3.2 -> 3.4.0)
#12 3.005   - Updating idna (3.7 -> 3.10)
#12 3.006   - Updating lxml (5.2.2 -> 5.3.0)
#12 3.007   - Updating paramiko (3.4.0 -> 3.5.0)
#12 3.008   - Updating rpds-py (0.19.0 -> 0.21.0)
#12 3.009   - Updating setuptools (71.1.0 -> 75.6.0)
#12 3.010   - Updating urllib3 (2.2.2 -> 2.2.3)
#12 150.2   - Updating amqp (5.2.0 -> 5.3.1)
#12 150.2   - Updating ncclient (0.6.15 -> 0.6.16)
#12 150.2   - Updating ntc-templates (6.0.0 -> 6.1.0)
#12 150.2   - Updating prompt-toolkit (3.0.47 -> 3.0.48)
#12 150.2   - Updating pyparsing (3.1.2 -> 3.2.0)
#12 150.2   - Installing ruamel-yaml-clib (0.2.12)
#12 150.2   - Updating sqlparse (0.5.1 -> 0.5.2)
#12 150.2   - Updating transitions (0.9.1 -> 0.9.2)
#12 150.2   - Updating tzdata (2024.1 -> 2024.2)
#12 151.7   - Updating billiard (4.2.0 -> 4.2.1)
#12 151.7   - Updating jsonschema-specifications (2023.12.1 -> 2024.10.1)
#12 151.7   - Updating kombu (5.3.7 -> 5.4.2)
#12 151.7   - Installing mypy-extensions (1.0.0)
#12 151.7   - Updating netutils (1.9.1 -> 1.10.0)
#12 151.7   - Updating pycodestyle (2.12.0 -> 2.12.1)
#12 151.7   - Updating pyeapi (1.0.2 -> 1.0.4)
#12 151.7   - Updating pyjwt (2.8.0 -> 2.10.0)
#12 151.7   - Installing ruamel-yaml (0.18.6)
#12 151.7   - Updating ttp-templates (0.3.6 -> 0.3.7)
#12 152.9   - Installing annotated-types (0.7.0)
#12 152.9   - Installing anyio (4.6.2.post1)
#12 152.9   - Updating cron-descriptor (1.4.3 -> 1.4.5)
#12 152.9   - Updating drf-spectacular-sidecar (2024.7.1 -> 2024.11.1)
#12 152.9   - Installing httpcore (1.0.7)
#12 152.9   - Downgrading napalm (5.0.0 -> 4.1.0)
#12 152.9   - Installing nornir (3.4.1)
#12 152.9   - Downgrading packaging (24.1 -> 23.2)
#12 152.9   - Installing pydantic-core (2.27.1)
#12 152.9   - Updating redis (5.0.7 -> 5.2.0)
#12 153.5   - Installing decorator (5.1.1)
#12 153.5   - Installing httpx (0.27.0)
#12 153.5   - Installing nornir-jinja2 (0.2.0)
#12 153.5   - Installing nornir-napalm (0.4.0)
#12 153.5   - Installing nornir-netmiko (1.0.1)
#12 153.5   - Installing nornir-utils (0.2.0)
#12 153.5   - Installing ordered-set (4.1.0)
#12 153.5   - Updating psycopg2-binary (2.9.9 -> 2.9.10)
#12 153.5   - Installing py (1.11.0)
#12 153.5   - Installing pydantic (2.10.2)
#12 153.5   - Installing pynautobot (2.4.2)
#12 153.5   - Updating pyuwsgi (2.0.26 -> 2.0.28.post1)
#12 158.8   - Installing deepdiff (6.7.1)
#12 158.8   - Installing diffsync (2.0.1)
#12 158.8   - Installing jmespath (1.0.1)
#12 158.8   - Updating nautobot (2.3.6 /source/dist/nautobot-2.3.6-py3-none-any.whl -> 2.3.6)
#12 158.8   - Installing nornir-nautobot (3.2.0)
#12 158.8   - Installing retry (0.9.2)
#12 158.9 Installing /usr/local/lib/python3.12/site-packages/LICENSE over existing file
#12 158.9 Installing /usr/local/lib/python3.12/site-packages/README.md over existing file
#12 161.4   - Installing jdiff (0.0.6)
#12 161.4   - Installing nautobot-plugin-nornir (2.1.0)
#12 161.4   - Installing nautobot-ssot (3.2.0)
#12 161.4   - Installing zipp (3.21.0)
#12 161.5 Installing /usr/local/lib/python3.12/site-packages/CHANGELOG.md over existing file
#12 161.5 Installing /usr/local/lib/python3.12/site-packages/LICENSE over existing file
#12 162.2   - Installing nautobot-device-onboarding (4.1.0)
#12 162.2   - Installing toml (0.10.2)
#12 162.5
#12 162.5 Installing the current project: nautobot-docker-compose (0.1.1)
#12 162.5
#12 162.5 Warning: The current project could not be installed: No file/folder found for package nautobot-docker-compose
#12 162.5 If you do not want to install the current project use --no-root.
#12 162.5 If you want to use Poetry only for dependency management but not for packaging, you can disable package mode by setting package-mode = false in your pyproject.toml file.
#12 162.5 In a future version of Poetry this warning will become an error!
#12 162.9 Warning: poetry-plugin-export will not be installed by default in a future version of Poetry.
#12 162.9 In order to avoid a breaking change and make your automation forward-compatible, please install poetry-plugin-export explicitly. See https://python-poetry.org/docs/plugins/#using-plugins for details on how to install a plugin.
#12 162.9 To disable this warning run 'poetry config warnings.export false'.
#12 DONE 163.6s

#13 [nautobot builder 6/8] COPY ../jobs /opt/nautobot/jobs
#13 DONE 0.0s

#14 [nautobot builder 7/8] COPY ../config/nautobot_config.py /opt/nautobot/nautobot_config.py
#14 DONE 0.0s

#15 [nautobot builder 8/8] WORKDIR /source
#15 DONE 0.0s

#16 [nautobot nautobot 1/5] COPY --from=builder /tmp/dist /tmp/dist
#16 DONE 0.0s

#17 [nautobot nautobot 2/5] COPY --from=builder /opt/nautobot /opt/nautobot
#17 DONE 0.0s

#18 [nautobot nautobot 3/5] COPY --from=builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
#18 DONE 5.7s

#19 [nautobot nautobot 4/5] COPY --from=builder /usr/local/bin /usr/local/bin
#19 DONE 0.1s

#20 [nautobot nautobot 5/5] RUN pyuwsgi --cflags | sed 's/ /\n/g' | grep -e "^-DUWSGI_SSL$"
#20 0.192 -DUWSGI_SSL
#20 DONE 0.2s

#21 [nautobot] exporting to image
#21 exporting layers
#21 exporting layers 2.1s done
#21 writing image sha256:4064c0b7d1bc91487da876f74b2420e770aed5695adee7e18f96ca1ec9f08b35
#21 writing image sha256:4064c0b7d1bc91487da876f74b2420e770aed5695adee7e18f96ca1ec9f08b35 done
#21 naming to docker.io/yourrepo/nautobot-docker-compose:local done
#21 DONE 2.1s

#22 [nautobot] resolving provenance for metadata file
#22 DONE 0.0s
(nautobot-docker-compose-py3.10) nautobot-docker-compose$ nautobot-server post_upgrade
Performing database migrations...
Traceback (most recent call last):
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/nautobot/core/cli/__init__.py", line 293, in main
    execute_from_command_line([sys.argv[0], *unparsed_args])
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/nautobot/core/management/commands/post_upgrade.py", line 91, in handle
    call_command(
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/nautobot/core/checks.py", line 92, in check_postgresql_version
    server_version = conn.cursor().connection.info.server_version
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 330, in cursor
    return self._cursor()
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 306, in _cursor
    self.ensure_connection()
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 288, in ensure_connection
    with self.wrap_database_errors:
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(nautobot-docker-compose-py3.10) nautobot-docker-compose$ invoke stop debug
Stopping Nautobot...
Running docker compose command "down"
 Container nautobot-docker-compose-celery_beat-1  Stopping
 Container nautobot-docker-compose-celery_worker-1  Stopping
 Container nautobot-docker-compose-celery_worker-1  Stopped
 Container nautobot-docker-compose-celery_worker-1  Removing
 Container nautobot-docker-compose-celery_beat-1  Stopped
 Container nautobot-docker-compose-celery_beat-1  Removing
 Container nautobot-docker-compose-celery_beat-1  Removed
 Container nautobot-docker-compose-celery_worker-1  Removed
 Container nautobot-docker-compose-nautobot-1  Stopping
 Container nautobot-docker-compose-nautobot-1  Stopped
 Container nautobot-docker-compose-nautobot-1  Removing
 Container nautobot-docker-compose-nautobot-1  Removed
 Container nautobot-docker-compose-redis-1  Stopping
 Container nautobot-docker-compose-db-1  Stopping
 Container nautobot-docker-compose-db-1  Stopped
 Container nautobot-docker-compose-db-1  Removing
 Container nautobot-docker-compose-redis-1  Stopped
 Container nautobot-docker-compose-redis-1  Removing
 Container nautobot-docker-compose-redis-1  Removed
 Container nautobot-docker-compose-db-1  Removed
 Network nautobot-docker-compose_default  Removing
 Network nautobot-docker-compose_default  Removed
Starting Nautobot in debug mode...
Running docker compose command "up"
 Network nautobot-docker-compose_default  Creating
 Network nautobot-docker-compose_default  Created
 Container nautobot-docker-compose-redis-1  Creating
 Container nautobot-docker-compose-db-1  Creating
 Container nautobot-docker-compose-redis-1  Created
 Container nautobot-docker-compose-db-1  Created
 Container nautobot-docker-compose-nautobot-1  Creating
 Container nautobot-docker-compose-nautobot-1  Created
 Container nautobot-docker-compose-celery_beat-1  Creating
 Container nautobot-docker-compose-celery_worker-1  Creating
 Container nautobot-docker-compose-celery_beat-1  Created
 Container nautobot-docker-compose-celery_worker-1  Created
Attaching to celery_beat-1, celery_worker-1, db-1, nautobot-1, redis-1
redis-1          | 1:C 27 Nov 2024 02:49:59.772 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-1          | 1:C 27 Nov 2024 02:49:59.772 # Redis version=6.2.16, bits=64, commit=00000000, modified=0, pid=1, just started
redis-1          | 1:C 27 Nov 2024 02:49:59.772 # Configuration loaded
redis-1          | 1:M 27 Nov 2024 02:49:59.773 * monotonic clock: POSIX clock_gettime
redis-1          | 1:M 27 Nov 2024 02:49:59.774 * Running mode=standalone, port=6379.
redis-1          | 1:M 27 Nov 2024 02:49:59.774 # Server initialized
redis-1          | 1:M 27 Nov 2024 02:49:59.777 * Ready to accept connections
db-1             |
db-1             | PostgreSQL Database directory appears to contain a database; Skipping initialization
db-1             |
db-1             | 2024-11-27 02:49:59.939 UTC [1] LOG:  starting PostgreSQL 13.18 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
db-1             | 2024-11-27 02:49:59.939 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1             | 2024-11-27 02:49:59.939 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1             | 2024-11-27 02:49:59.944 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1             | 2024-11-27 02:49:59.949 UTC [25] LOG:  database system was interrupted; last known up at 2024-11-27 01:54:49 UTC
db-1             | 2024-11-27 02:50:00.141 UTC [25] LOG:  database system was not properly shut down; automatic recovery in progress
db-1             | 2024-11-27 02:50:00.143 UTC [25] LOG:  redo starts at 0/2268410
db-1             | 2024-11-27 02:50:00.144 UTC [25] LOG:  invalid record length at 0/2269330: wanted 24, got 0
db-1             | 2024-11-27 02:50:00.144 UTC [25] LOG:  redo done at 0/22692F8
db-1             | 2024-11-27 02:50:00.162 UTC [1] LOG:  database system is ready to accept connections
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 65, in load_plugin
nautobot-1       |     plugin = importlib.import_module(plugin_name)
nautobot-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
nautobot-1       |     return _bootstrap._gcd_import(name[level:], package, level)
nautobot-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
nautobot-1       | ModuleNotFoundError: No module named 'nautobot_golden_config'
nautobot-1       |
nautobot-1       | The above exception was the direct cause of the following exception:
nautobot-1       |
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/bin/nautobot-server", line 8, in <module>
nautobot-1       |     sys.exit(main())
nautobot-1       |              ^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 292, in main
nautobot-1       |     load_settings(args.config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 139, in load_settings
nautobot-1       |     _preprocess_settings(module, config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 125, in _preprocess_settings
nautobot-1       |     load_plugins(settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 55, in load_plugins
nautobot-1       |     load_plugin(plugin_name, settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 68, in load_plugin
nautobot-1       |     raise PluginNotFound(
nautobot-1       | nautobot.extras.plugins.exceptions.PluginNotFound: Unable to import plugin nautobot_golden_config: Module not found. Check that the plugin module has been installed within the correct Python environment.
nautobot-1       | ⏳ Waiting on DB... (0s / 30s)
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 65, in load_plugin
nautobot-1       |     plugin = importlib.import_module(plugin_name)
nautobot-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
nautobot-1       |     return _bootstrap._gcd_import(name[level:], package, level)
nautobot-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
nautobot-1       | ModuleNotFoundError: No module named 'nautobot_golden_config'
nautobot-1       |
nautobot-1       | The above exception was the direct cause of the following exception:
nautobot-1       |
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/bin/nautobot-server", line 8, in <module>
nautobot-1       |     sys.exit(main())
nautobot-1       |              ^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 292, in main
nautobot-1       |     load_settings(args.config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 139, in load_settings
nautobot-1       |     _preprocess_settings(module, config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 125, in _preprocess_settings
nautobot-1       |     load_plugins(settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 55, in load_plugins
nautobot-1       |     load_plugin(plugin_name, settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 68, in load_plugin
nautobot-1       |     raise PluginNotFound(
nautobot-1       | nautobot.extras.plugins.exceptions.PluginNotFound: Unable to import plugin nautobot_golden_config: Module not found. Check that the plugin module has been installed within the correct Python environment.
nautobot-1       | ⏳ Waiting on DB... (3s / 30s)
celery_beat-1    | Traceback (most recent call last):
celery_beat-1    |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 65, in load_plugin
celery_beat-1    |     plugin = importlib.import_module(plugin_name)
celery_beat-1    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_beat-1    |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
celery_beat-1    |     return _bootstrap._gcd_import(name[level:], package, level)
celery_beat-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_beat-1    |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
celery_beat-1    |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
celery_beat-1    |   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
celery_beat-1    | ModuleNotFoundError: No module named 'nautobot_golden_config'
celery_beat-1    |
celery_beat-1    | The above exception was the direct cause of the following exception:
celery_beat-1    |
celery_beat-1    | Traceback (most recent call last):
celery_beat-1    |   File "/usr/local/bin/nautobot-server", line 8, in <module>
celery_beat-1    |     sys.exit(main())
celery_beat-1    |              ^^^^^^
celery_beat-1    |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 292, in main
celery_beat-1    |     load_settings(args.config_path)
celery_beat-1    |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 139, in load_settings
celery_beat-1    |     _preprocess_settings(module, config_path)
celery_beat-1    |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 125, in _preprocess_settings
celery_beat-1    |     load_plugins(settings)
celery_beat-1    |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 55, in load_plugins
celery_beat-1    |     load_plugin(plugin_name, settings)
celery_beat-1    |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 68, in load_plugin
celery_beat-1    |     raise PluginNotFound(
celery_beat-1    | nautobot.extras.plugins.exceptions.PluginNotFound: Unable to import plugin nautobot_golden_config: Module not found. Check that the plugin module has been installed within the correct Python environment.
celery_worker-1  | Traceback (most recent call last):
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 65, in load_plugin
celery_worker-1  |     plugin = importlib.import_module(plugin_name)
celery_worker-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker-1  |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
celery_worker-1  |     return _bootstrap._gcd_import(name[level:], package, level)
celery_worker-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker-1  |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
celery_worker-1  |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
celery_worker-1  |   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
celery_worker-1  | ModuleNotFoundError: No module named 'nautobot_golden_config'
celery_worker-1  |
celery_worker-1  | The above exception was the direct cause of the following exception:
celery_worker-1  |
celery_worker-1  | Traceback (most recent call last):
celery_worker-1  |   File "/usr/local/bin/nautobot-server", line 8, in <module>
celery_worker-1  |     sys.exit(main())
celery_worker-1  |              ^^^^^^
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 292, in main
celery_worker-1  |     load_settings(args.config_path)
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 139, in load_settings
celery_worker-1  |     _preprocess_settings(module, config_path)
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 125, in _preprocess_settings
celery_worker-1  |     load_plugins(settings)
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 55, in load_plugins
celery_worker-1  |     load_plugin(plugin_name, settings)
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 68, in load_plugin
celery_worker-1  |     raise PluginNotFound(
celery_worker-1  | nautobot.extras.plugins.exceptions.PluginNotFound: Unable to import plugin nautobot_golden_config: Module not found. Check that the plugin module has been installed within the correct Python environment.
celery_beat-1    |
celery_worker-1  |
celery_beat-1 exited with code 1
celery_worker-1 exited with code 1
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 65, in load_plugin
nautobot-1       |     plugin = importlib.import_module(plugin_name)
nautobot-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
nautobot-1       |     return _bootstrap._gcd_import(name[level:], package, level)
nautobot-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
nautobot-1       | ModuleNotFoundError: No module named 'nautobot_golden_config'
nautobot-1       |
nautobot-1       | The above exception was the direct cause of the following exception:
nautobot-1       |
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/bin/nautobot-server", line 8, in <module>
nautobot-1       |     sys.exit(main())
nautobot-1       |              ^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 292, in main
nautobot-1       |     load_settings(args.config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 139, in load_settings
nautobot-1       |     _preprocess_settings(module, config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 125, in _preprocess_settings
nautobot-1       |     load_plugins(settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 55, in load_plugins
nautobot-1       |     load_plugin(plugin_name, settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 68, in load_plugin
nautobot-1       |     raise PluginNotFound(
nautobot-1       | nautobot.extras.plugins.exceptions.PluginNotFound: Unable to import plugin nautobot_golden_config: Module not found. Check that the plugin module has been installed within the correct Python environment.
nautobot-1       | ⏳ Waiting on DB... (6s / 30s)
Gracefully stopping... (press Ctrl+C again to force)
 Container nautobot-docker-compose-celery_worker-1  Stopping
 Container nautobot-docker-compose-celery_beat-1  Stopping
 Container nautobot-docker-compose-celery_worker-1  Stopped
 Container nautobot-docker-compose-celery_beat-1  Stopped
 Container nautobot-docker-compose-nautobot-1  Stopping
 Container nautobot-docker-compose-nautobot-1  Stopped
 Container nautobot-docker-compose-redis-1  Stopping
 Container nautobot-docker-compose-db-1  Stopping
 Container nautobot-docker-compose-db-1  Stopped
 Container nautobot-docker-compose-redis-1  Stopped
canceled
(nautobot-docker-compose-py3.10) nautobot-docker-compose$ poetry add nautobot-golden-config
Using version ^2.1.2 for nautobot-golden-config

Updating dependencies
Resolving dependencies... (0.2s)

The current project's supported Python range (>=3.9,<3.13) is not compatible with some of the required packages Python requirement:
  - nautobot-golden-config requires Python <3.12,>=3.8, so it will not be satisfied for Python >=3.12,<3.13

Because no versions of nautobot-golden-config match >2.1.2,<3.0.0
 and nautobot-golden-config (2.1.2) requires Python <3.12,>=3.8, nautobot-golden-config is forbidden.
So, because nautobot-docker-compose depends on nautobot-golden-config (^2.1.2), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For nautobot-golden-config, a possible solution would be to set the `python` property to ">=3.9,<3.12"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
(nautobot-docker-compose-py3.10) nautobot-docker-compose$
(nautobot-docker-compose-py3.10) nautobot-docker-compose$ python --version
Python 3.10.4
(nautobot-docker-compose-py3.10) nautobot-docker-compose$ which python
/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/bin/python
(nautobot-docker-compose-py3.10) nautobot-docker-compose$ poetry update
Updating dependencies
Resolving dependencies... (0.5s)

The current project's supported Python range (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
  - nautobot requires Python <3.13,>=3.8, so it will not be satisfied for Python >=3.13,<4.0

Because nautobot-docker-compose depends on nautobot (2.3.6) which requires Python <3.13,>=3.8, version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For nautobot, a possible solution would be to set the `python` property to ">=3.10,<3.13"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
(nautobot-docker-compose-py3.10) nautobot-docker-compose$ poetry update
Updating dependencies
Resolving dependencies... (0.0s)

The current project's supported Python range (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
  - nautobot requires Python <3.13,>=3.8, so it will not be satisfied for Python >=3.13,<4.0

Because nautobot-docker-compose depends on nautobot (2.3.6) which requires Python <3.13,>=3.8, version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For nautobot, a possible solution would be to set the `python` property to ">=3.10,<3.13"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
(nautobot-docker-compose-py3.10) nautobot-docker-compose$ poetry update
Updating dependencies
Resolving dependencies... (14.4s)

No dependencies to install or update

Writing lock file
(nautobot-docker-compose-py3.10) nautobot-docker-compose$ poetry add nautobot-golden-config
Using version ^2.1.2 for nautobot-golden-config

Updating dependencies
Resolving dependencies... (0.0s)

The current project's supported Python range (>=3.10,<3.13) is not compatible with some of the required packages Python requirement:
  - nautobot-golden-config requires Python <3.12,>=3.8, so it will not be satisfied for Python >=3.12,<3.13

Because no versions of nautobot-golden-config match >2.1.2,<3.0.0
 and nautobot-golden-config (2.1.2) requires Python <3.12,>=3.8, nautobot-golden-config is forbidden.
So, because nautobot-docker-compose depends on nautobot-golden-config (^2.1.2), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For nautobot-golden-config, a possible solution would be to set the `python` property to ">=3.10,<3.12"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
(nautobot-docker-compose-py3.10) nautobot-docker-compose$ poetry update
Updating dependencies
Resolving dependencies... (4.2s)

No dependencies to install or update

Writing lock file
(nautobot-docker-compose-py3.10) nautobot-docker-compose$ poetry add nautobot-golden-config
The following packages are already present in the pyproject.toml and will be skipped:

  - nautobot-golden-config

If you want to update it to the latest compatible version, you can use `poetry update package`.
If you prefer to upgrade it to the latest available version, you can use `poetry add package@latest`.

Nothing to add.
(nautobot-docker-compose-py3.10) nautobot-docker-compose$
(nautobot-docker-compose-py3.10) nautobot-docker-compose$
(nautobot-docker-compose-py3.10) nautobot-docker-compose$
(nautobot-docker-compose-py3.10) nautobot-docker-compose$ nautobot-server post_upgrade
Performing database migrations...
Traceback (most recent call last):
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/bin/nautobot-server", line 8, in <module>
    sys.exit(main())
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/nautobot/core/cli/__init__.py", line 293, in main
    execute_from_command_line([sys.argv[0], *unparsed_args])
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/nautobot/core/management/commands/post_upgrade.py", line 91, in handle
    call_command(
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 100, in handle
    self.check(databases=[database])
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/nautobot/core/checks.py", line 92, in check_postgresql_version
    server_version = conn.cursor().connection.info.server_version
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 330, in cursor
    return self._cursor()
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 306, in _cursor
    self.ensure_connection()
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 288, in ensure_connection
    with self.wrap_database_errors:
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 289, in ensure_connection
    self.connect()
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/base/base.py", line 270, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/django/db/backends/postgresql/base.py", line 275, in get_new_connection
    connection = self.Database.connect(**conn_params)
  File "/Users/jabelk/Library/Caches/pypoetry/virtualenvs/nautobot-docker-compose-gRtuJhB6-py3.10/lib/python3.10/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: connection to server at "localhost" (::1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?

(nautobot-docker-compose-py3.10) nautobot-docker-compose$ invoke stop debug
Stopping Nautobot...
Running docker compose command "down"
 Container nautobot-docker-compose-celery_worker-1  Stopping
 Container nautobot-docker-compose-celery_beat-1  Stopping
 Container nautobot-docker-compose-celery_beat-1  Stopped
 Container nautobot-docker-compose-celery_beat-1  Removing
 Container nautobot-docker-compose-celery_worker-1  Stopped
 Container nautobot-docker-compose-celery_worker-1  Removing
 Container nautobot-docker-compose-celery_beat-1  Removed
 Container nautobot-docker-compose-celery_worker-1  Removed
 Container nautobot-docker-compose-nautobot-1  Stopping
 Container nautobot-docker-compose-nautobot-1  Stopped
 Container nautobot-docker-compose-nautobot-1  Removing
 Container nautobot-docker-compose-nautobot-1  Removed
 Container nautobot-docker-compose-redis-1  Stopping
 Container nautobot-docker-compose-db-1  Stopping
 Container nautobot-docker-compose-redis-1  Stopped
 Container nautobot-docker-compose-redis-1  Removing
 Container nautobot-docker-compose-db-1  Stopped
 Container nautobot-docker-compose-db-1  Removing
 Container nautobot-docker-compose-redis-1  Removed
 Container nautobot-docker-compose-db-1  Removed
 Network nautobot-docker-compose_default  Removing
 Network nautobot-docker-compose_default  Removed
Starting Nautobot in debug mode...
Running docker compose command "up"
 Network nautobot-docker-compose_default  Creating
 Network nautobot-docker-compose_default  Created
 Container nautobot-docker-compose-redis-1  Creating
 Container nautobot-docker-compose-db-1  Creating
 Container nautobot-docker-compose-db-1  Created
 Container nautobot-docker-compose-redis-1  Created
 Container nautobot-docker-compose-nautobot-1  Creating
 Container nautobot-docker-compose-nautobot-1  Created
 Container nautobot-docker-compose-celery_beat-1  Creating
 Container nautobot-docker-compose-celery_worker-1  Creating
 Container nautobot-docker-compose-celery_beat-1  Created
 Container nautobot-docker-compose-celery_worker-1  Created
Attaching to celery_beat-1, celery_worker-1, db-1, nautobot-1, redis-1
redis-1          | 1:C 27 Nov 2024 03:00:14.135 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis-1          | 1:C 27 Nov 2024 03:00:14.135 # Redis version=6.2.16, bits=64, commit=00000000, modified=0, pid=1, just started
redis-1          | 1:C 27 Nov 2024 03:00:14.135 # Configuration loaded
redis-1          | 1:M 27 Nov 2024 03:00:14.135 * monotonic clock: POSIX clock_gettime
redis-1          | 1:M 27 Nov 2024 03:00:14.136 * Running mode=standalone, port=6379.
redis-1          | 1:M 27 Nov 2024 03:00:14.136 # Server initialized
redis-1          | 1:M 27 Nov 2024 03:00:14.139 * Ready to accept connections
db-1             |
db-1             | PostgreSQL Database directory appears to contain a database; Skipping initialization
db-1             |
db-1             | 2024-11-27 03:00:14.275 UTC [1] LOG:  starting PostgreSQL 13.18 on aarch64-unknown-linux-musl, compiled by gcc (Alpine 13.2.1_git20240309) 13.2.1 20240309, 64-bit
db-1             | 2024-11-27 03:00:14.275 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1             | 2024-11-27 03:00:14.275 UTC [1] LOG:  listening on IPv6 address "::", port 5432
db-1             | 2024-11-27 03:00:14.279 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1             | 2024-11-27 03:00:14.282 UTC [26] LOG:  database system was shut down at 2024-11-27 02:50:23 UTC
db-1             | 2024-11-27 03:00:14.294 UTC [1] LOG:  database system is ready to accept connections
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 65, in load_plugin
nautobot-1       |     plugin = importlib.import_module(plugin_name)
nautobot-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
nautobot-1       |     return _bootstrap._gcd_import(name[level:], package, level)
nautobot-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
nautobot-1       | ModuleNotFoundError: No module named 'nautobot_golden_config'
nautobot-1       |
nautobot-1       | The above exception was the direct cause of the following exception:
nautobot-1       |
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/bin/nautobot-server", line 8, in <module>
nautobot-1       |     sys.exit(main())
nautobot-1       |              ^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 292, in main
nautobot-1       |     load_settings(args.config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 139, in load_settings
nautobot-1       |     _preprocess_settings(module, config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 125, in _preprocess_settings
nautobot-1       |     load_plugins(settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 55, in load_plugins
nautobot-1       |     load_plugin(plugin_name, settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 68, in load_plugin
nautobot-1       |     raise PluginNotFound(
nautobot-1       | nautobot.extras.plugins.exceptions.PluginNotFound: Unable to import plugin nautobot_golden_config: Module not found. Check that the plugin module has been installed within the correct Python environment.
nautobot-1       | ⏳ Waiting on DB... (0s / 30s)
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 65, in load_plugin
nautobot-1       |     plugin = importlib.import_module(plugin_name)
nautobot-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
nautobot-1       |     return _bootstrap._gcd_import(name[level:], package, level)
nautobot-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
nautobot-1       | ModuleNotFoundError: No module named 'nautobot_golden_config'
nautobot-1       |
nautobot-1       | The above exception was the direct cause of the following exception:
nautobot-1       |
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/bin/nautobot-server", line 8, in <module>
nautobot-1       |     sys.exit(main())
nautobot-1       |              ^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 292, in main
nautobot-1       |     load_settings(args.config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 139, in load_settings
nautobot-1       |     _preprocess_settings(module, config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 125, in _preprocess_settings
nautobot-1       |     load_plugins(settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 55, in load_plugins
nautobot-1       |     load_plugin(plugin_name, settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 68, in load_plugin
nautobot-1       |     raise PluginNotFound(
nautobot-1       | nautobot.extras.plugins.exceptions.PluginNotFound: Unable to import plugin nautobot_golden_config: Module not found. Check that the plugin module has been installed within the correct Python environment.
nautobot-1       | ⏳ Waiting on DB... (3s / 30s)
celery_beat-1    | Traceback (most recent call last):
celery_beat-1    |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 65, in load_plugin
celery_beat-1    |     plugin = importlib.import_module(plugin_name)
celery_beat-1    |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_beat-1    |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
celery_beat-1    |     return _bootstrap._gcd_import(name[level:], package, level)
celery_beat-1    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_beat-1    |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
celery_beat-1    |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
celery_beat-1    |   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
celery_beat-1    | ModuleNotFoundError: No module named 'nautobot_golden_config'
celery_beat-1    |
celery_beat-1    | The above exception was the direct cause of the following exception:
celery_beat-1    |
celery_beat-1    | Traceback (most recent call last):
celery_beat-1    |   File "/usr/local/bin/nautobot-server", line 8, in <module>
celery_beat-1    |     sys.exit(main())
celery_beat-1    |              ^^^^^^
celery_beat-1    |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 292, in main
celery_beat-1    |     load_settings(args.config_path)
celery_beat-1    |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 139, in load_settings
celery_beat-1    |     _preprocess_settings(module, config_path)
celery_beat-1    |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 125, in _preprocess_settings
celery_beat-1    |     load_plugins(settings)
celery_beat-1    |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 55, in load_plugins
celery_beat-1    |     load_plugin(plugin_name, settings)
celery_beat-1    |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 68, in load_plugin
celery_beat-1    |     raise PluginNotFound(
celery_beat-1    | nautobot.extras.plugins.exceptions.PluginNotFound: Unable to import plugin nautobot_golden_config: Module not found. Check that the plugin module has been installed within the correct Python environment.
celery_worker-1  | Traceback (most recent call last):
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 65, in load_plugin
celery_worker-1  |     plugin = importlib.import_module(plugin_name)
celery_worker-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker-1  |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
celery_worker-1  |     return _bootstrap._gcd_import(name[level:], package, level)
celery_worker-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
celery_worker-1  |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
celery_worker-1  |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
celery_worker-1  |   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
celery_worker-1  | ModuleNotFoundError: No module named 'nautobot_golden_config'
celery_worker-1  |
celery_worker-1  | The above exception was the direct cause of the following exception:
celery_worker-1  |
celery_worker-1  | Traceback (most recent call last):
celery_worker-1  |   File "/usr/local/bin/nautobot-server", line 8, in <module>
celery_worker-1  |     sys.exit(main())
celery_worker-1  |              ^^^^^^
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 292, in main
celery_worker-1  |     load_settings(args.config_path)
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 139, in load_settings
celery_worker-1  |     _preprocess_settings(module, config_path)
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 125, in _preprocess_settings
celery_worker-1  |     load_plugins(settings)
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 55, in load_plugins
celery_worker-1  |     load_plugin(plugin_name, settings)
celery_worker-1  |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 68, in load_plugin
celery_worker-1  |     raise PluginNotFound(
celery_worker-1  | nautobot.extras.plugins.exceptions.PluginNotFound: Unable to import plugin nautobot_golden_config: Module not found. Check that the plugin module has been installed within the correct Python environment.
celery_beat-1    |
celery_worker-1  |
celery_beat-1 exited with code 1
celery_worker-1 exited with code 1
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 65, in load_plugin
nautobot-1       |     plugin = importlib.import_module(plugin_name)
nautobot-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
nautobot-1       |     return _bootstrap._gcd_import(name[level:], package, level)
nautobot-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
nautobot-1       | ModuleNotFoundError: No module named 'nautobot_golden_config'
nautobot-1       |
nautobot-1       | The above exception was the direct cause of the following exception:
nautobot-1       |
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/bin/nautobot-server", line 8, in <module>
nautobot-1       |     sys.exit(main())
nautobot-1       |              ^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 292, in main
nautobot-1       |     load_settings(args.config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 139, in load_settings
nautobot-1       |     _preprocess_settings(module, config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 125, in _preprocess_settings
nautobot-1       |     load_plugins(settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 55, in load_plugins
nautobot-1       |     load_plugin(plugin_name, settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 68, in load_plugin
nautobot-1       |     raise PluginNotFound(
nautobot-1       | nautobot.extras.plugins.exceptions.PluginNotFound: Unable to import plugin nautobot_golden_config: Module not found. Check that the plugin module has been installed within the correct Python environment.
nautobot-1       | ⏳ Waiting on DB... (6s / 30s)
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 65, in load_plugin
nautobot-1       |     plugin = importlib.import_module(plugin_name)
nautobot-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
nautobot-1       |     return _bootstrap._gcd_import(name[level:], package, level)
nautobot-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
nautobot-1       | ModuleNotFoundError: No module named 'nautobot_golden_config'
nautobot-1       |
nautobot-1       | The above exception was the direct cause of the following exception:
nautobot-1       |
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/bin/nautobot-server", line 8, in <module>
nautobot-1       |     sys.exit(main())
nautobot-1       |              ^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 292, in main
nautobot-1       |     load_settings(args.config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 139, in load_settings
nautobot-1       |     _preprocess_settings(module, config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 125, in _preprocess_settings
nautobot-1       |     load_plugins(settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 55, in load_plugins
nautobot-1       |     load_plugin(plugin_name, settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 68, in load_plugin
nautobot-1       |     raise PluginNotFound(
nautobot-1       | nautobot.extras.plugins.exceptions.PluginNotFound: Unable to import plugin nautobot_golden_config: Module not found. Check that the plugin module has been installed within the correct Python environment.
nautobot-1       | ⏳ Waiting on DB... (9s / 30s)
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 65, in load_plugin
nautobot-1       |     plugin = importlib.import_module(plugin_name)
nautobot-1       |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
nautobot-1       |     return _bootstrap._gcd_import(name[level:], package, level)
nautobot-1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
nautobot-1       |   File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
nautobot-1       | ModuleNotFoundError: No module named 'nautobot_golden_config'
nautobot-1       |
nautobot-1       | The above exception was the direct cause of the following exception:
nautobot-1       |
nautobot-1       | Traceback (most recent call last):
nautobot-1       |   File "/usr/local/bin/nautobot-server", line 8, in <module>
nautobot-1       |     sys.exit(main())
nautobot-1       |              ^^^^^^
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 292, in main
nautobot-1       |     load_settings(args.config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 139, in load_settings
nautobot-1       |     _preprocess_settings(module, config_path)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/core/cli/__init__.py", line 125, in _preprocess_settings
nautobot-1       |     load_plugins(settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 55, in load_plugins
nautobot-1       |     load_plugin(plugin_name, settings)
nautobot-1       |   File "/usr/local/lib/python3.12/site-packages/nautobot/extras/plugins/utils.py", line 68, in load_plugin
nautobot-1       |     raise PluginNotFound(
nautobot-1       | nautobot.extras.plugins.exceptions.PluginNotFound: Unable to import plugin nautobot_golden_config: Module not found. Check that the plugin module has been installed within the correct Python environment.
nautobot-1       | ⏳ Waiting on DB... (12s / 30s)
Gracefully stopping... (press Ctrl+C again to force)
 Container nautobot-docker-compose-celery_beat-1  Stopping
 Container nautobot-docker-compose-celery_worker-1  Stopping
 Container nautobot-docker-compose-celery_beat-1  Stopped
 Container nautobot-docker-compose-celery_worker-1  Stopped
 Container nautobot-docker-compose-nautobot-1  Stopping
 Container nautobot-docker-compose-nautobot-1  Stopped
 Container nautobot-docker-compose-db-1  Stopping
 Container nautobot-docker-compose-redis-1  Stopping
 Container nautobot-docker-compose-db-1  Stopped
 Container nautobot-docker-compose-redis-1  Stopped
canceled
(nautobot-docker-compose-py3.10) nautobot-docker-compose$